improve codegen test output

diff --git a/tests/codegen/tests b/tests/codegen/tests
--- a/tests/codegen/tests
+++ b/tests/codegen/tests
@@ -1,13 +1,17 @@
 #!/bin/bash
 
 exitcode=0
+red=$(tput setaf 1)
+grn=$(tput setaf 2)
+rst=$(tput sgr0)
+intml=../../intml
 
 expect () {
     echo expect $1 = $2
     $1
     result=$?
     if [[ $result == $2 ]]; then
-        echo pass
+        echo ${grn}pass${rst}
     else
         echo FAIL: $1 = $result
         exitcode=$((1 + $exitcode))
@@ -36,20 +40,25 @@ fi
 
 expect2 () {
     code="$1"
+    stmp=$(mktemp)
     otmp=$(mktemp)
-    echo "$code" | ../../intml - | as -o $otmp --
-    ${LD} ${LDFLAGS} -o a.out $otmp ${LDLIBS}
-    ./a.out
-    result=$?
-    if [[ $result == $2 ]]; then
-        echo pass
+    if (echo "$code" | $intml -o $stmp -); then
+        as -o $otmp $stmp && ${LD} ${LDFLAGS} -o a.out $otmp ${LDLIBS}
+        ./a.out
+        result=$?
+        if [[ $result == $2 ]]; then
+            echo "${grn}pass${rst}"
+        else
+            echo "${red}FAIL:${rst} '$1'"
+            echo "  expected: $2"
+            echo "  actual:   $result"
+            exitcode=$((1 + $exitcode))
+        fi
     else
-        echo "FAIL: '$1'"
-        echo "  expected: $2"
-        echo "  actual:   $result"
+        echo "${red}FAILED${rst} to compile '$1'"
         exitcode=$((1 + $exitcode))
     fi
-    rm -f a.out $otmp
+    rm -f a.out $otmp $stmp
 }
 
 expect2 "
